--------------------------------------------------------------------------
-- ProMaNet - Estructura limpia para Oracle Autonomous Database (ATP)
-- Fase A: tablas + secuencias + indices unicos (SIN llaves foraneas).
-- Las llaves foraneas van en atp_02_llaves_foraneas.sql, DESPUES de cargar
-- los datos. Ejecutar este archivo conectado como el usuario RRHH.
--------------------------------------------------------------------------

-- ===================== SECUENCIAS =====================
CREATE SEQUENCE "DEMO_CUST_SEQ"        MINVALUE 1 INCREMENT BY 1 START WITH 21 CACHE 20 NOCYCLE;
CREATE SEQUENCE "DEMO_ORDER_ITEMS_SEQ" MINVALUE 1 INCREMENT BY 1 START WITH 61 CACHE 20 NOCYCLE;
CREATE SEQUENCE "DEMO_ORD_SEQ"         MINVALUE 1 INCREMENT BY 1 START WITH 11 CACHE 20 NOCYCLE;
CREATE SEQUENCE "DEMO_PROD_SEQ"        MINVALUE 1 INCREMENT BY 1 START WITH 21 CACHE 20 NOCYCLE;
CREATE SEQUENCE "DEMO_USERS_SEQ"       MINVALUE 1 INCREMENT BY 1 START WITH 21 CACHE 20 NOCYCLE;
CREATE SEQUENCE "REP_BIOM_ATRASO_SEQ"  MINVALUE 1 INCREMENT BY 1 START WITH 1  CACHE 20 NOCYCLE;
CREATE SEQUENCE "SEQ_INV_DETALLE"      MINVALUE 1 INCREMENT BY 1 START WITH 11 NOCACHE   NOCYCLE;

-- ===================== TABLAS =====================

CREATE TABLE "ADM_CAB_AGENDA" (
  "ID_ADM_CAB_AGENDA" NUMBER(*,0) NOT NULL,
  "ID_USUARIO" NUMBER(*,0),
  "FECHA_AGE_INI" TIMESTAMP (6),
  "HORA_AGE_INI" VARCHAR2(20),
  "HORA_AGE_FIN" VARCHAR2(20),
  "ID_CLIENTE" NUMBER(*,0),
  "OBSERVACION" VARCHAR2(500),
  "ESTADO_AGENDA" VARCHAR2(20),
  "ESTADO" VARCHAR2(1),
  "AREA" VARCHAR2(100)
);

CREATE TABLE "ADM_DEPARTAMENTO" (
  "ID_DEPARTAMENTO" VARCHAR2(20) NOT NULL,
  "DEPARTAMENTO" VARCHAR2(100),
  "DESCRIPCION" VARCHAR2(200),
  "ESTADO" VARCHAR2(1)
);

CREATE TABLE "ADM_DET_AGENDA" (
  "ID_ADM_DET_AGENDA" NUMBER NOT NULL,
  "ID_ADM_CAB_AGENDA" NUMBER,
  "ID_USUARIO" NUMBER,
  "ESTADO" VARCHAR2(1),
  "APELLIDOS" VARCHAR2(200),
  "NOMBRES" VARCHAR2(200),
  "DEPARTAMENTO" VARCHAR2(200)
);

CREATE TABLE "ADM_NOTIFICACIONES" (
  "IDNOTIFICACIONES" NUMBER NOT NULL,
  "FECHA_INGRESO" DATE,
  "COMPANIA" VARCHAR2(200),
  "NOMBRES" VARCHAR2(100),
  "APELLIDOS" VARCHAR2(100),
  "ROL" VARCHAR2(25),
  "JEFE_INMEDIATO" VARCHAR2(100),
  "ACTIVIDADES" VARCHAR2(200),
  "ID_USUARIO_SOLICITANTE" NUMBER,
  "ESTADO" VARCHAR2(20),
  "FECHA_NOTIFICACION" DATE,
  "OBSERVACIONES" VARCHAR2(100),
  "KIT_MK" VARCHAR2(100)
);

CREATE TABLE "APP_PERMISO" (
  "ID_PERMISO" NUMBER,
  "CODIGO" VARCHAR2(60) NOT NULL,
  "MODULO" VARCHAR2(40) NOT NULL,
  "DESCRIPCION" VARCHAR2(200),
  "ESTADO" CHAR(1) DEFAULT 'A' NOT NULL,
  CONSTRAINT "PK_APP_PERMISO" PRIMARY KEY ("ID_PERMISO"),
  CONSTRAINT "UQ_APP_PERMISO_CODIGO" UNIQUE ("CODIGO")
);

CREATE TABLE "APP_DEPARTAMENTO_PERMISO" (
  "DEPARTAMENTO" VARCHAR2(100) NOT NULL,
  "ID_PERMISO" NUMBER NOT NULL,
  "TIPO" CHAR(1) DEFAULT 'D' NOT NULL,
  CONSTRAINT "CK_APP_DEPTO_PERMISO_TIPO" CHECK (TIPO IN ('G','D')),
  CONSTRAINT "PK_APP_DEPTO_PERMISO" PRIMARY KEY ("DEPARTAMENTO", "ID_PERMISO")
);

CREATE TABLE "APP_ROL_PERMISO" (
  "IDROL" NUMBER NOT NULL,
  "ID_PERMISO" NUMBER NOT NULL,
  CONSTRAINT "PK_APP_ROL_PERMISO" PRIMARY KEY ("IDROL", "ID_PERMISO")
);

CREATE TABLE "APP_USUARIO_PERMISO" (
  "IDUSUARIO" NUMBER NOT NULL,
  "ID_PERMISO" NUMBER NOT NULL,
  "TIPO" CHAR(1) NOT NULL,
  CONSTRAINT "CK_AUP_TIPO" CHECK (TIPO IN ('G','D')),
  CONSTRAINT "PK_APP_USUARIO_PERMISO" PRIMARY KEY ("IDUSUARIO", "ID_PERMISO")
);

CREATE TABLE "CLIENTE" (
  "IDCLIENTE" NUMBER(10,0) NOT NULL,
  "CLIENTE" VARCHAR2(100),
  "DIRECCION" VARCHAR2(100),
  "ESTADO" VARCHAR2(1),
  "RUC" VARCHAR2(13),
  "CONTACTO" VARCHAR2(150),
  "TELEFONO" VARCHAR2(30),
  "EMAIL" VARCHAR2(50),
  CONSTRAINT "CK_CLIENTE_ESTADO" CHECK (estado in('a','i')),
  CONSTRAINT "PK_IDCLIENTE" PRIMARY KEY ("IDCLIENTE")
);

CREATE TABLE "CLK_ASISTENCIA_CAB" (
  "IDASIS_CAB" NUMBER NOT NULL,
  "ID_USUARIO" NUMBER
);

CREATE TABLE "CLK_ASISTENCIA_DET" (
  "IDASIS_DET" NUMBER,
  "IDASIS_CAB" NUMBER,
  "HORA" DATE,
  "TIPO_ASISTENCIA" VARCHAR2(20)
);

CREATE TABLE "COMPANIA" (
  "IDCOMPANIA" NUMBER(10,0) NOT NULL,
  "RUC" VARCHAR2(13),
  "COMPANIA" VARCHAR2(100),
  "ESTADO" VARCHAR2(1),
  CONSTRAINT "CK_COMPANIA_ESTADO" CHECK (estado in('a','i')),
  CONSTRAINT "PK_IDCOMPANIA1" PRIMARY KEY ("IDCOMPANIA")
);

CREATE TABLE "CTRL_ANTICIPOS" (
  "ID_CTRL_ANTICIPO" NUMBER NOT NULL,
  "ID_USUARIO" NUMBER,
  "SUELDO" FLOAT(126),
  "FECHA_SOLICITUD" DATE,
  "ANTICIPO" FLOAT(126),
  "ID_DEPARTAMENTO" NUMBER,
  "ESTADO" VARCHAR2(20),
  CONSTRAINT "CTRL_ANTICIPOS_PK" PRIMARY KEY ("ID_CTRL_ANTICIPO")
);

CREATE TABLE "CTRL_FECHA_CORTE_ANTICIPO" (
  "ID_FECHA_CORTE" NUMBER NOT NULL,
  "FECHA_CORTE" DATE,
  "ESTADO" VARCHAR2(20),
  "ID_USUARIO" NUMBER,
  CONSTRAINT "CTRL_FECHA_CORTE_ANTICIPO_PK" PRIMARY KEY ("ID_FECHA_CORTE")
);

CREATE TABLE "INV_ASIGNACION" (
  "IDINV_ASIGNACION" NUMBER NOT NULL,
  "IDINVEQUIPO" NUMBER,
  "FECHAASIGNACION" DATE,
  "IDUSUARIO" NUMBER,
  "ESTADO" VARCHAR2(20),
  "FECHADEVOLUCION" DATE,
  CONSTRAINT "INV_PK" PRIMARY KEY ("IDINV_ASIGNACION")
);

CREATE TABLE "INV_CATEGORIA" (
  "INV_ID_CATEGORIA" NUMBER NOT NULL,
  "DESCRIPCION" VARCHAR2(100),
  "ESTADO" VARCHAR2(1),
  CONSTRAINT "INV_CATEGORIA_PK" PRIMARY KEY ("INV_ID_CATEGORIA")
);

CREATE TABLE "INV_CURRIER" (
  "ID_CURRIER" NUMBER,
  "APELLIDOS" VARCHAR2(50),
  "NOMBRES" VARCHAR2(50),
  "DIRECCION" VARCHAR2(100),
  "CONTACTO" VARCHAR2(50),
  "ESTADO" VARCHAR2(1)
);

CREATE TABLE "INV_DISPOSITIVO" (
  "ID_DISPOSITIVO" NUMBER NOT NULL,
  "DISPOSITIVO" VARCHAR2(150),
  "ESTADO" VARCHAR2(20),
  CONSTRAINT "INV_DISPOSITIVO_PK" PRIMARY KEY ("ID_DISPOSITIVO")
);

CREATE TABLE "INV_EQUIPOS" (
  "IDINVEQUIPO" NUMBER NOT NULL,
  "FECHACOMPRA" DATE,
  "UBICACIONOFICINA" VARCHAR2(50),
  "DEPARTAMENTO" VARCHAR2(50),
  "MARCA" VARCHAR2(100),
  "MODELO" VARCHAR2(100),
  "SERIAL" VARCHAR2(100),
  "PROCESADOR" VARCHAR2(100),
  "HDD" VARCHAR2(50),
  "RAM" VARCHAR2(50),
  "PANTALLA" VARCHAR2(100),
  "OBSERVACIONES" VARCHAR2(1000),
  "ESTADO" VARCHAR2(2),
  "EMPRESA" VARCHAR2(100),
  "DISPOSITIVO" VARCHAR2(50),
  "ESTADO_AI" VARCHAR2(2),
  "FICHERO" VARCHAR2(300),
  "ID_CURRIER" NUMBER,
  CONSTRAINT "INV_EQUIPOS_PK" PRIMARY KEY ("IDINVEQUIPO")
);

CREATE TABLE "INV_PRODUCTO" (
  "ID_PRODUCTO" NUMBER NOT NULL,
  "INV_ID_CATEGORIA" NUMBER,
  "DESCRIPCION" VARCHAR2(200),
  "UNIDAD" VARCHAR2(100),
  "ID_UNIDAD" NUMBER,
  CONSTRAINT "INV_PRODUCTO_PK" PRIMARY KEY ("ID_PRODUCTO")
);

CREATE TABLE "INV_PROVEEDOR" (
  "ID_PROVEEDOR" NUMBER NOT NULL,
  "IDENTIFICACION" VARCHAR2(13),
  "RAZON_SOCIAL" VARCHAR2(200),
  "DIRECCION" VARCHAR2(100),
  "TELEFONO" VARCHAR2(20),
  "CORREO" VARCHAR2(100),
  "CONTACTO" VARCHAR2(100),
  "ESTADO" VARCHAR2(1),
  CONSTRAINT "INV_PROVEEDOR_PK" PRIMARY KEY ("ID_PROVEEDOR")
);

CREATE TABLE "INV_SUMINISTRO_EGRESO_CAB" (
  "ID_SUMINISTRO_EGRESO_CAB" NUMBER NOT NULL,
  "ID_USUARIO" NUMBER,
  "FECHA_SOLICITUD" DATE,
  "ID_DEPARTAMENTO" NUMBER,
  "ID_USUARIO_AUTO" NUMBER,
  "ESTADO_SOLICITUD" VARCHAR2(20),
  CONSTRAINT "INV_SUMINISTRO_EGRESO_CAB_PK" PRIMARY KEY ("ID_SUMINISTRO_EGRESO_CAB")
);

CREATE TABLE "INV_SUMINISTRO_EGRESO_DET" (
  "ID_SUMINISTRO_EGRESO_DET" NUMBER NOT NULL,
  "ID_PRODUCTO" NUMBER,
  "CANTIDAD" NUMBER,
  "ID_SUMINISTRO_EGRESO_CAB" NUMBER,
  CONSTRAINT "INV_SUMINISTRO_EGRESO_DET_PK" PRIMARY KEY ("ID_SUMINISTRO_EGRESO_DET")
);

CREATE TABLE "INV_SUMINISTRO_EXISTENCIA" (
  "ID_SUMINISTRO_EXISTENCIA" NUMBER NOT NULL,
  "ID_PRODUCTO" NUMBER,
  "EXISTENCIA" NUMBER,
  CONSTRAINT "INV_SUMINISTRO_EXISTENCIA_PK" PRIMARY KEY ("ID_SUMINISTRO_EXISTENCIA")
);

CREATE TABLE "INV_SUMINISTRO_INGRESO_CAB" (
  "ID_SUMINISTRO_INGRESO_CAB" NUMBER NOT NULL,
  "ID_USUARIO" NUMBER,
  "FECHA_COMPRA" DATE,
  "FECHA_PEDIDO" DATE,
  "FECHA_RECIBIDO" DATE,
  "ESTADO" VARCHAR2(1),
  "ID_INV_PROVEEDOR" NUMBER,
  "NUMERO_FACTURA" VARCHAR2(20),
  CONSTRAINT "INV_SUMINISTRO_INGRESO_CAB_PK" PRIMARY KEY ("ID_SUMINISTRO_INGRESO_CAB")
);

CREATE TABLE "INV_SUMINISTRO_INGRESO_DET" (
  "ID_SUMINISTRO_INGRESO_DET" NUMBER NOT NULL,
  "ID_PRODUCTO" NUMBER,
  "CANTIDAD" NUMBER,
  "ID_SUMINISTRO_INGRESO_CAB" NUMBER,
  CONSTRAINT "INV_SUMINISTRO_INGRESO_DET_PK" PRIMARY KEY ("ID_SUMINISTRO_INGRESO_DET")
);

CREATE TABLE "INV_UNIDAD_MEDIDA" (
  "ID_UNIDAD_MEDIDA" NUMBER NOT NULL,
  "UNIDAD" VARCHAR2(50),
  "DESCRIPCION" VARCHAR2(200),
  "ESTADO" VARCHAR2(20),
  CONSTRAINT "INV_UNIDAD_MEDIDA_PK" PRIMARY KEY ("ID_UNIDAD_MEDIDA")
);

CREATE TABLE "INV_UNIDAD_NEGOCIO" (
  "ID_UNIDAD_NEGOCIO" VARCHAR2(20) NOT NULL,
  "UNIDAD_NEGOCIO" VARCHAR2(100),
  "DESCRIPCION" VARCHAR2(200),
  CONSTRAINT "INV_UNIDAD_NEGOCIO_PK" PRIMARY KEY ("ID_UNIDAD_NEGOCIO")
);

CREATE TABLE "MOV_DESTINO" (
  "ID_DESTINO" NUMBER,
  "DESCRIPCION" VARCHAR2(150) NOT NULL,
  "ESTADO" CHAR(1) DEFAULT 'A' NOT NULL,
  CONSTRAINT "PK_MOV_DESTINO" PRIMARY KEY ("ID_DESTINO")
);

CREATE TABLE "MOV_MOTIVO" (
  "ID_MOTIVO" NUMBER,
  "DESCRIPCION" VARCHAR2(100) NOT NULL,
  "ESTADO" CHAR(1) DEFAULT 'A' NOT NULL,
  CONSTRAINT "PK_MOV_MOTIVO" PRIMARY KEY ("ID_MOTIVO")
);

CREATE TABLE "MOV_MOVILIZADOR" (
  "ID_MOVILIZADOR" NUMBER,
  "NOMBRE" VARCHAR2(100) NOT NULL,
  "ESTADO" CHAR(1) DEFAULT 'A' NOT NULL,
  CONSTRAINT "PK_MOV_MOVILIZADOR" PRIMARY KEY ("ID_MOVILIZADOR")
);

CREATE TABLE "MOV_SOLICITUD" (
  "ID_MOV_SOLICITUD" NUMBER,
  "ID_MOVILIZADOR" NUMBER NOT NULL,
  "ID_MOTIVO" NUMBER NOT NULL,
  "FECHA" DATE NOT NULL,
  "HORA_INICIO" VARCHAR2(5) NOT NULL,
  "HORA_FIN" VARCHAR2(5) NOT NULL,
  "IDUSUARIO" NUMBER NOT NULL,
  "ID_DEPARTAMENTO" NUMBER NOT NULL,
  "COMENTARIO" VARCHAR2(500),
  "ESTADO" VARCHAR2(15) DEFAULT 'PENDIENTE' NOT NULL,
  "FECHA_SOLICITUD" DATE DEFAULT SYSDATE NOT NULL,
  "IDUSUARIO_GESTIONA" NUMBER,
  "FECHA_GESTION" DATE,
  "MOTIVO_RECHAZO" VARCHAR2(500),
  "ID_DESTINO" NUMBER,
  CONSTRAINT "PK_MOV_SOLICITUD" PRIMARY KEY ("ID_MOV_SOLICITUD"),
  CONSTRAINT "CK_MOVSOL_ESTADO" CHECK (ESTADO IN ('PENDIENTE','APROBADA','RECHAZADA','CANCELADA','MOVILIZADO'))
);

CREATE TABLE "REG_BIOM_MOTIVO" (
  "ID_BIOM_MOTIVO" NUMBER NOT NULL,
  "DESCRIPCION" VARCHAR2(45),
  "ESTADO" VARCHAR2(20)
);

CREATE TABLE "REP_BIOM_ATRASO" (
  "ID_REP_BIOM_ATRASO" NUMBER NOT NULL,
  "ID_USUARIO" NUMBER,
  "FECHA_NOTIFICACION" DATE,
  "ID_REP_BIOM_MOTIVO" NUMBER NOT NULL,
  "ESTADO" VARCHAR2(20),
  "OBSERVACION" VARCHAR2(45),
  CONSTRAINT "REP_BIOM_ATRASO_PK" PRIMARY KEY ("ID_REP_BIOM_ATRASO")
);

CREATE TABLE "REPGASASIG" (
  "IDREPGASASIG" NUMBER NOT NULL,
  "IDUSUARIO" NUMBER NOT NULL,
  "IDUSUARIOASIG" NUMBER NOT NULL,
  CONSTRAINT "REPGASASIG_PK" PRIMARY KEY ("IDREPGASASIG")
);

CREATE TABLE "REP_GASCAB" (
  "IDREPGASCAB" NUMBER,
  "IDUSUARIO" NUMBER,
  "FECHA" DATE,
  "TOTAL" FLOAT(126),
  "APROBADO" VARCHAR2(1)
);

CREATE TABLE "REPGASCAB" (
  "IDREPGASCAB" NUMBER(10,0) NOT NULL,
  "IDUSUARIO" NUMBER(10,0) NOT NULL,
  "FECHA" VARCHAR2(10),
  "TOTAL" FLOAT(126),
  "APROBADO" VARCHAR2(1),
  CONSTRAINT "PK_IDREPGASCAB" PRIMARY KEY ("IDREPGASCAB")
);

CREATE TABLE "REP_GASDET" (
  "IDREPGASDET" NUMBER,
  "IDCLIENTE" NUMBER,
  "FECHA" DATE,
  "VALOR" FLOAT(126),
  "TRABREALIZADO" VARCHAR2(1000),
  "TOTALIM" FLOAT(126),
  "TOTMOVI" FLOAT(126),
  "IDREPGASCAB" NUMBER
);

CREATE TABLE "REPGASDET" (
  "IDREPGASDET" NUMBER(10,0) NOT NULL,
  "IDCLIENTE" NUMBER(10,0) NOT NULL,
  "FECHA" VARCHAR2(100),
  "VALOR" FLOAT(126),
  "TRABREALIZADO" VARCHAR2(1000),
  "TOTALIM" FLOAT(126),
  "TOTMOVI" FLOAT(126),
  "IDREPGASCAB" NUMBER(10,0),
  CONSTRAINT "PK_IDREPGASDET" PRIMARY KEY ("IDREPGASDET")
);

CREATE TABLE "ROL" (
  "IDROL" NUMBER(10,0) NOT NULL,
  "CARGO" VARCHAR2(50) NOT NULL,
  "ABREVIATURA" VARCHAR2(10),
  "ACTIVIDADES" VARCHAR2(200),
  "ESTADO" VARCHAR2(1),
  CONSTRAINT "CK_ROL_ESTADO" CHECK (estado in('a','i')),
  CONSTRAINT "PK_IDROL" PRIMARY KEY ("IDROL")
);

CREATE TABLE "SOP_SOPORTE_CAB" (
  "IDSOPORTE" NUMBER NOT NULL,
  "IDUSUARIO" NUMBER,
  "IDEQUIPO" NUMBER,
  "FECHA_SOLICITUD" DATE,
  "SOPORTE" VARCHAR2(1000),
  "PRIORIDAD" VARCHAR2(20),
  "ESTADO" VARCHAR2(20),
  "REPORTE" VARCHAR2(1000),
  "FECHA_REPORTE" DATE,
  "TECNICO" VARCHAR2(45)
);

CREATE TABLE "TODOAREA" (
  "IDTODOAREA" NUMBER NOT NULL,
  "DESCRIPCION" VARCHAR2(50),
  "ABREVIATURA" VARCHAR2(10),
  "ACTIVIDADES" VARCHAR2(200),
  "ESTADO" VARCHAR2(1) NOT NULL,
  CONSTRAINT "CK_TODOAREA_ESTADO" CHECK (ESTADO in('A','I')),
  CONSTRAINT "TODOAREA_PK" PRIMARY KEY ("IDTODOAREA")
);

CREATE TABLE "TODOASIGTAREA" (
  "IDTODOASIGTAREA" NUMBER NOT NULL,
  "IDUSUARIO" NUMBER NOT NULL,
  "IDTODODETTRAB" NUMBER NOT NULL,
  "FECHAHORAASIG" DATE,
  "ESTADO" VARCHAR2(1) NOT NULL,
  CONSTRAINT "TODOASIGTAREA_PK" PRIMARY KEY ("IDTODOASIGTAREA")
);

CREATE TABLE "TODOASIGTRAB" (
  "IDTODOASIGTRAB" NUMBER NOT NULL,
  "IDUSUARIO" NUMBER NOT NULL,
  "IDTODOCABTRAB" NUMBER NOT NULL,
  CONSTRAINT "TODOASIGTRAB_PK" PRIMARY KEY ("IDTODOASIGTRAB")
);

CREATE TABLE "TODOCABGRUPO" (
  "IDTODOCABGRUPO" NUMBER NOT NULL,
  "NOMBREGRUPO" VARCHAR2(50),
  "ESTADO" VARCHAR2(1),
  CONSTRAINT "TODOCABGRUPO_PK" PRIMARY KEY ("IDTODOCABGRUPO")
);

CREATE TABLE "TODO_CAB_TAREAS" (
  "ID_TODO_CAB_TAREAS" NUMBER NOT NULL,
  "ID_ADM_DEPARTAMENTO" NUMBER,
  "TAREA" VARCHAR2(200),
  "DESCRIPCION" VARCHAR2(500),
  "ESTADO" VARCHAR2(1)
);

CREATE TABLE "TODOCABTRAB" (
  "IDTODOCAB" NUMBER(10,0) NOT NULL,
  "IDUSUARIO" NUMBER(10,0) NOT NULL,
  "DESCRIPCION" VARCHAR2(1000),
  "TRABAJO" VARCHAR2(500),
  "FECHAINCIO" DATE,
  "FECHAFIN" DATE,
  "FECHAHORAASIG" DATE,
  "FECHALEGAL" DATE,
  "FECHACONTRATO" DATE,
  "IDCLIENTE" NUMBER NOT NULL,
  "ESTADO" VARCHAR2(1) NOT NULL,
  "COMENTARIO" VARCHAR2(500),
  "IDTODOAREA" NUMBER NOT NULL,
  "ESTTRAB" VARCHAR2(20),
  "IDTODOCABGRUPO" NUMBER,
  "IDJEFEASIG" NUMBER,
  "IDCABTAREA" NUMBER,
  CONSTRAINT "CK_TODOCABTRAB_ESTADO" CHECK (ESTADO in('A','I')),
  CONSTRAINT "PK_IDTODOCAB" PRIMARY KEY ("IDTODOCAB")
);

CREATE TABLE "TODOCABTRABINDV" (
  "IDTODOCABINDV" NUMBER NOT NULL,
  "IDUSUARIO" NUMBER NOT NULL,
  "DESCRIPCION" VARCHAR2(600),
  "TRABAJO" VARCHAR2(100),
  "FECHAINICIO" DATE,
  "FECHAFIN" DATE,
  "FECHAHORAASIG" DATE,
  "FECHALEGAL" DATE,
  "FECHACONTRATO" DATE,
  "IDCLIENTE" NUMBER,
  "ESTADO" VARCHAR2(1),
  "COMENTARIO" VARCHAR2(200),
  "IDTODOAREA" NUMBER,
  "ESTTRAB" VARCHAR2(20),
  "IDJEFEASIG" NUMBER
);

CREATE TABLE "TODODETATRABINDV" (
  "IDTODODETINDV" NUMBER(10,0) NOT NULL,
  "IDTODOCABTRAINDV" NUMBER(10,0),
  "DETALLE" VARCHAR2(500),
  "FECHAHORAINICIO" DATE,
  "EST_DET_TRAB" VARCHAR2(1)
);

CREATE TABLE "TODODETGRUPO" (
  "IDTODODETGRUPO" NUMBER NOT NULL,
  "IDTODOCABGRUPO" NUMBER NOT NULL,
  "IDUSUARIO" NUMBER NOT NULL,
  "ESTADO" VARCHAR2(1),
  CONSTRAINT "TODODETGRUPO_PK" PRIMARY KEY ("IDTODODETGRUPO")
);

CREATE TABLE "TODODETTAREA" (
  "IDTODODETTAREA" NUMBER NOT NULL,
  "IDTODODETTRAB" NUMBER NOT NULL,
  "FECHAHORAINICIO" DATE,
  "FECHAHORAFIN" DATE,
  "ESTADO" VARCHAR2(1) NOT NULL,
  "DETALLE" VARCHAR2(300),
  CONSTRAINT "CK_TODODETTAREA_ESTADO" CHECK (ESTADO in('A','I')),
  CONSTRAINT "TODODETTAREA_PK" PRIMARY KEY ("IDTODODETTAREA")
);

CREATE TABLE "TODO_DET_TAREAS" (
  "ID_TODO_DET_TAREAS" NUMBER NOT NULL,
  "ID_TODO_CAB_TAREAS" NUMBER,
  "DESCRIPCION" VARCHAR2(500),
  "ESTADO" VARCHAR2(1),
  "ORDEN" NUMBER
);

CREATE TABLE "TODODETTRAB" (
  "IDTODODET" NUMBER(10,0) NOT NULL,
  "IDTODOCABTRAB" NUMBER(10,0) NOT NULL,
  "DETALLE" VARCHAR2(500),
  "FECHAHORAINICIO" DATE,
  "ESTADO" VARCHAR2(1),
  "FECHAHORAFIN" DATE,
  "EST_DET_TRAB" VARCHAR2(1),
  CONSTRAINT "CK_TODODETTRAB_ESTADO" CHECK (ESTADO in('A','I')),
  CONSTRAINT "PK_IDTODODET" PRIMARY KEY ("IDTODODET")
);

CREATE TABLE "TODOROL" (
  "IDROLTODO" NUMBER(10,0) NOT NULL,
  "CARGOTODO" VARCHAR2(50) NOT NULL,
  "ABREVIATURA" VARCHAR2(10),
  "ACTIVIDADES" VARCHAR2(200),
  "ESTADO" VARCHAR2(1)
);

CREATE TABLE "USUARIO" (
  "IDUSUARIO" NUMBER(10,0) NOT NULL,
  "NOMBRE" VARCHAR2(50),
  "APELLIDOS" VARCHAR2(50),
  "TELEFONO" VARCHAR2(20),
  "EMAIL" VARCHAR2(300),
  "USUARIO" VARCHAR2(30),
  "CONTRASENA" VARCHAR2(20),
  "IDCOMPANIA" NUMBER(10,0),
  "IDROL" NUMBER(10,0),
  "ESTADO" VARCHAR2(3),
  "IDROLTODO" NUMBER,
  "ID_ADM_DEPARTAMENTO" NUMBER(2,0),
  "SUELDO" NUMBER,
  CONSTRAINT "CK_USUARIO_ESTADO" CHECK (estado in('a','i')),
  CONSTRAINT "USUARIO_PK" PRIMARY KEY ("IDUSUARIO")
);

CREATE TABLE "USUARIO_FOTOS" (
  "IDUSUARIO" NUMBER NOT NULL,
  "IMAGEN" BLOB
);

-- ===================== INDICES UNICOS FUNCIONALES =====================
CREATE UNIQUE INDEX "UX_MOV_DESTINO_DESC" ON "MOV_DESTINO" (UPPER(TRIM("DESCRIPCION")));
CREATE UNIQUE INDEX "UX_MOV_MOTIVO_DESC"  ON "MOV_MOTIVO"  (UPPER(TRIM("DESCRIPCION")));
