--------------------------------------------------------------------------
-- ProMaNet - Llaves foraneas para Oracle Autonomous Database (ATP)
-- Fase C: ejecutar DESPUES de cargar los datos (Fase B).
-- Cada ALTER es independiente; si alguna fallara por datos historicos
-- inconsistentes, se puede omitir esa sin afectar a las demas.
-- Ejecutar conectado como el usuario RRHH, con "Ejecutar Script" (F5).
--------------------------------------------------------------------------

ALTER TABLE "APP_DEPARTAMENTO_PERMISO" ADD CONSTRAINT "FK_APP_DEPTO_PERMISO" FOREIGN KEY ("ID_PERMISO") REFERENCES "APP_PERMISO" ("ID_PERMISO");

ALTER TABLE "APP_ROL_PERMISO" ADD CONSTRAINT "FK_ARP_PERMISO" FOREIGN KEY ("ID_PERMISO") REFERENCES "APP_PERMISO" ("ID_PERMISO");
ALTER TABLE "APP_ROL_PERMISO" ADD CONSTRAINT "FK_ARP_ROL" FOREIGN KEY ("IDROL") REFERENCES "ROL" ("IDROL");

ALTER TABLE "APP_USUARIO_PERMISO" ADD CONSTRAINT "FK_AUP_PERMISO" FOREIGN KEY ("ID_PERMISO") REFERENCES "APP_PERMISO" ("ID_PERMISO");
ALTER TABLE "APP_USUARIO_PERMISO" ADD CONSTRAINT "FK_AUP_USUARIO" FOREIGN KEY ("IDUSUARIO") REFERENCES "USUARIO" ("IDUSUARIO");

ALTER TABLE "MOV_SOLICITUD" ADD CONSTRAINT "FK_MOVSOL_MOVILIZADOR" FOREIGN KEY ("ID_MOVILIZADOR") REFERENCES "MOV_MOVILIZADOR" ("ID_MOVILIZADOR");
ALTER TABLE "MOV_SOLICITUD" ADD CONSTRAINT "FK_MOVSOL_MOTIVO" FOREIGN KEY ("ID_MOTIVO") REFERENCES "MOV_MOTIVO" ("ID_MOTIVO");
ALTER TABLE "MOV_SOLICITUD" ADD CONSTRAINT "FK_MOVSOL_USUARIO" FOREIGN KEY ("IDUSUARIO") REFERENCES "USUARIO" ("IDUSUARIO");
ALTER TABLE "MOV_SOLICITUD" ADD CONSTRAINT "FK_MOVSOL_USUARIO_GEST" FOREIGN KEY ("IDUSUARIO_GESTIONA") REFERENCES "USUARIO" ("IDUSUARIO");
ALTER TABLE "MOV_SOLICITUD" ADD CONSTRAINT "FK_MOVSOL_DESTINO" FOREIGN KEY ("ID_DESTINO") REFERENCES "MOV_DESTINO" ("ID_DESTINO");

ALTER TABLE "REPGASASIG" ADD CONSTRAINT "FK_IDUSUARIOREP" FOREIGN KEY ("IDUSUARIO") REFERENCES "USUARIO" ("IDUSUARIO");

ALTER TABLE "REPGASCAB" ADD CONSTRAINT "FK_IDUSUARIORE" FOREIGN KEY ("IDUSUARIO") REFERENCES "USUARIO" ("IDUSUARIO");

ALTER TABLE "REPGASDET" ADD CONSTRAINT "FK_IDCLIENTERE" FOREIGN KEY ("IDCLIENTE") REFERENCES "CLIENTE" ("IDCLIENTE");

ALTER TABLE "TODOASIGTAREA" ADD CONSTRAINT "FK_IDTODODETTRAB" FOREIGN KEY ("IDTODODETTRAB") REFERENCES "TODODETTRAB" ("IDTODODET");
ALTER TABLE "TODOASIGTAREA" ADD CONSTRAINT "FK_IDUSUARIOASITAREA" FOREIGN KEY ("IDUSUARIO") REFERENCES "USUARIO" ("IDUSUARIO");

ALTER TABLE "TODOASIGTRAB" ADD CONSTRAINT "FK_IDTODOCABTRABASIG" FOREIGN KEY ("IDTODOCABTRAB") REFERENCES "TODOCABTRAB" ("IDTODOCAB");
ALTER TABLE "TODOASIGTRAB" ADD CONSTRAINT "FK_IDUSUARIOASIGTRAB" FOREIGN KEY ("IDUSUARIO") REFERENCES "USUARIO" ("IDUSUARIO");

ALTER TABLE "TODOCABTRAB" ADD CONSTRAINT "FK_IDCLIENTETODO" FOREIGN KEY ("IDCLIENTE") REFERENCES "CLIENTE" ("IDCLIENTE");
ALTER TABLE "TODOCABTRAB" ADD CONSTRAINT "FK_IDUSUARIO" FOREIGN KEY ("IDUSUARIO") REFERENCES "USUARIO" ("IDUSUARIO");

ALTER TABLE "TODODETTRAB" ADD CONSTRAINT "FK_IDTODOCABTRAB" FOREIGN KEY ("IDTODOCABTRAB") REFERENCES "TODOCABTRAB" ("IDTODOCAB");

ALTER TABLE "USUARIO" ADD CONSTRAINT "FK_IDCOMPANIA" FOREIGN KEY ("IDCOMPANIA") REFERENCES "COMPANIA" ("IDCOMPANIA");
