-- =====================================================================
-- Conceder a SMORAN (usuario real: 'smoran', IDUSUARIO=162) acceso
-- completo al modulo de Inventario, via APP_USUARIO_PERMISO, sin
-- tocar su cargo.
--
-- YA EJECUTADO el 2026-07-08 usando IDUSUARIO=162 directamente
-- (el filtro por USUARIO='SMORAN' no encontraba la fila porque el
-- valor real esta en minusculas: 'smoran'). Este archivo queda
-- actualizado con UPPER() para poder reutilizarlo sin ese problema.
-- =====================================================================

DELETE FROM APP_USUARIO_PERMISO
WHERE IDUSUARIO = (SELECT IDUSUARIO FROM USUARIO WHERE UPPER(USUARIO) = 'SMORAN')
  AND ID_PERMISO IN (1,2,3,4,5,6);

INSERT INTO APP_USUARIO_PERMISO (IDUSUARIO, ID_PERMISO, TIPO)
    SELECT IDUSUARIO, 1, 'G' FROM USUARIO WHERE UPPER(USUARIO) = 'SMORAN';
INSERT INTO APP_USUARIO_PERMISO (IDUSUARIO, ID_PERMISO, TIPO)
    SELECT IDUSUARIO, 2, 'G' FROM USUARIO WHERE UPPER(USUARIO) = 'SMORAN';
INSERT INTO APP_USUARIO_PERMISO (IDUSUARIO, ID_PERMISO, TIPO)
    SELECT IDUSUARIO, 3, 'G' FROM USUARIO WHERE UPPER(USUARIO) = 'SMORAN';
INSERT INTO APP_USUARIO_PERMISO (IDUSUARIO, ID_PERMISO, TIPO)
    SELECT IDUSUARIO, 4, 'G' FROM USUARIO WHERE UPPER(USUARIO) = 'SMORAN';
INSERT INTO APP_USUARIO_PERMISO (IDUSUARIO, ID_PERMISO, TIPO)
    SELECT IDUSUARIO, 5, 'G' FROM USUARIO WHERE UPPER(USUARIO) = 'SMORAN';
INSERT INTO APP_USUARIO_PERMISO (IDUSUARIO, ID_PERMISO, TIPO)
    SELECT IDUSUARIO, 6, 'G' FROM USUARIO WHERE UPPER(USUARIO) = 'SMORAN';

COMMIT;

-- Verificar:
SELECT u.USUARIO, p.CODIGO, up.TIPO
FROM APP_USUARIO_PERMISO up
JOIN USUARIO u ON u.IDUSUARIO = up.IDUSUARIO
JOIN APP_PERMISO p ON p.ID_PERMISO = up.ID_PERMISO
WHERE UPPER(u.USUARIO) = 'SMORAN'
ORDER BY p.ID_PERMISO;

-- SMORAN debe volver a iniciar sesion para que aplique.
