-- =====================================================================
-- Modulo de Solicitud de Vacaciones -- Fase 3: tabla de solicitudes
--
-- No agrega permisos nuevos: VACACIONES_SOLICITAR (Fase 2) ya cubre
-- "solicitar" y VACACIONES_GESTIONAR (ya concedido a SMORAN) cubrira
-- la aprobacion de Administracion/Recepcion cuando se construya esa
-- pantalla. Esta fase solo crea donde vive la solicitud en si.
-- =====================================================================

CREATE TABLE VAC_SOLICITUD (
    ID_SOLICITUD              NUMBER NOT NULL,
    ID_USUARIO                NUMBER NOT NULL,
    ID_JEFE_DIRECTO           NUMBER NOT NULL,
    NUM_PERIODO               NUMBER NOT NULL,
    FECHA_SOLICITUD           DATE DEFAULT SYSDATE NOT NULL,
    FECHA_DESDE               DATE NOT NULL,
    FECHA_HASTA               DATE NOT NULL,
    FECHA_REINCORPORACION     DATE NOT NULL,
    DIAS_SOLICITADOS          NUMBER NOT NULL,
    ESTADO                    VARCHAR2(20) DEFAULT 'PENDIENTE_JEFE' NOT NULL,
    ID_USUARIO_APRUEBA_JEFE   NUMBER,
    FECHA_APROBACION_JEFE     DATE,
    COMENTARIO_JEFE           VARCHAR2(500),
    ID_USUARIO_APRUEBA_ADMIN  NUMBER,
    FECHA_APROBACION_ADMIN    DATE,
    DIAS_APROBADOS            NUMBER,
    COMENTARIO_ADMIN          VARCHAR2(500),
    ID_USUARIO_RECIBE         NUMBER,
    FECHA_RECEPCION           DATE,
    CONSTRAINT PK_VAC_SOLICITUD PRIMARY KEY (ID_SOLICITUD),
    CONSTRAINT FK_VAC_SOL_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(IDUSUARIO),
    CONSTRAINT FK_VAC_SOL_JEFE FOREIGN KEY (ID_JEFE_DIRECTO) REFERENCES USUARIO(IDUSUARIO),
    CONSTRAINT FK_VAC_SOL_APR_JEFE FOREIGN KEY (ID_USUARIO_APRUEBA_JEFE) REFERENCES USUARIO(IDUSUARIO),
    CONSTRAINT FK_VAC_SOL_APR_ADMIN FOREIGN KEY (ID_USUARIO_APRUEBA_ADMIN) REFERENCES USUARIO(IDUSUARIO),
    CONSTRAINT FK_VAC_SOL_RECIBE FOREIGN KEY (ID_USUARIO_RECIBE) REFERENCES USUARIO(IDUSUARIO),
    CONSTRAINT CK_VAC_SOL_ESTADO CHECK (ESTADO IN
        ('PENDIENTE_JEFE','RECHAZADO_JEFE','PENDIENTE_ADMIN','RECHAZADO_ADMIN','APROBADO','RECIBIDO','CANCELADO')),
    CONSTRAINT CK_VAC_SOL_FECHAS CHECK (FECHA_HASTA >= FECHA_DESDE)
);

COMMIT;
