-- =====================================================================
-- Modulo de Solicitud de Vacaciones -- carga masiva de cedula y
-- empresa de afiliacion IESS desde PATRONAL_AE_2.xlsx (36 empleados,
-- 10 empresas patronales).
--
-- REQUIERE haber corrido antes:
--   024_vacaciones_cedula.sql          (columna CEDULA)
--   025_vacaciones_empresa_iess.sql    (columna EMPRESA_IESS)
--
-- COMO SE ARMO EL MATCH: el excel no trae ID_USUARIO, asi que cada
-- MERGE busca al empleado por nombre completo, comparando
-- APELLIDOS||' '||NOMBRE contra el texto del excel (el excel viene en
-- orden "apellidos nombres", al reves de como esta pantalla arma
-- u.NOMBRE||' '||u.APELLIDOS). Si el nombre no calza exactamente con
-- lo que hay en USUARIO (tilde distinta, orden distinto, empleado no
-- existe en el sistema, etc.) el MERGE simplemente no hace nada para
-- esa fila -- no falla, pero tampoco avisa. Por eso el SELECT de
-- verificacion al final es obligatorio: compara cuantos de los 36
-- quedaron cargados contra cuantos se esperaba.
--
-- CASO ESPECIAL: PARRALES SOLIS UKLES XAVIER aparece en el excel dos
-- veces, con dos empresas distintas (BUSINESS ADVISOR NETWORK BUADNET
-- S.A. con aviso de entrada 01/08/2025, y ARTHURS AUDIT GLOBAL
-- HURSDIT S.A. con aviso de entrada 15/07/2024). Se asumio que la
-- empresa vigente es la del aviso MAS RECIENTE (BUADNET) y por eso es
-- la unica que se carga aqui. Si esto no es correcto (por ejemplo si
-- en realidad sigue afiliado a HURSDIT, o esta afiliado a ambas),
-- avisar para corregir el registro manualmente en la pantalla de
-- Configuracion.
-- =====================================================================

-- Varios nombres de empresa traen '&' (BUADNET TAX&FINANCE, KAVODLEX
-- LEGAL & CORPORATE...). SQL*Plus / SQL Developer interpretan eso como
-- el inicio de una variable de sustitucion y detienen el script
-- pidiendo un valor -- SET DEFINE OFF lo desactiva para que el '&' se
-- guarde tal cual, como texto literal.
SET DEFINE OFF;

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'MALDONADO CONDOR DERIAN AARON'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0943184416',
    EMPRESA_IESS = 'ADMININSOLUTIONS S.A.S',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0943184416', 'ADMININSOLUTIONS S.A.S', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'MORAN ALVARADO SCARLETTE MELINA'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0944211325',
    EMPRESA_IESS = 'ADMININSOLUTIONS S.A.S',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0944211325', 'ADMININSOLUTIONS S.A.S', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'NARANJO ESPINOZA GABRIELA STEPHANIA'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0954548954',
    EMPRESA_IESS = 'ADMININSOLUTIONS S.A.S',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0954548954', 'ADMININSOLUTIONS S.A.S', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'ARAMBULO CEPEDA OSCAR DANIEL'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0919973156',
    EMPRESA_IESS = 'ARTHURS AUDIT GLOBAL HURSDIT S.A.',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0919973156', 'ARTHURS AUDIT GLOBAL HURSDIT S.A.', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'BARRERA SOLIS LUIGGI ENRIQUE'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0925874570',
    EMPRESA_IESS = 'ARTHURS AUDIT GLOBAL HURSDIT S.A.',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0925874570', 'ARTHURS AUDIT GLOBAL HURSDIT S.A.', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'DUARTE MARIN RAQUEL GUADALUPE'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0923455950',
    EMPRESA_IESS = 'ARTHURS AUDIT GLOBAL HURSDIT S.A.',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0923455950', 'ARTHURS AUDIT GLOBAL HURSDIT S.A.', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'MONCAYO CALERO VICTOR ALFONSO'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0915143671',
    EMPRESA_IESS = 'ARTHURS AUDIT GLOBAL HURSDIT S.A.',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0915143671', 'ARTHURS AUDIT GLOBAL HURSDIT S.A.', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'TROYA COBEÑA KEVIN ALEXANDER'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0955309315',
    EMPRESA_IESS = 'ARTHURS AUDIT GLOBAL HURSDIT S.A.',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0955309315', 'ARTHURS AUDIT GLOBAL HURSDIT S.A.', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'URIBE AVILA DIANA CAROLINA'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0951771476',
    EMPRESA_IESS = 'ARTHURS AUDIT GLOBAL HURSDIT S.A.',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0951771476', 'ARTHURS AUDIT GLOBAL HURSDIT S.A.', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'VELOZ GALARZA LUIS ANDRES'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0919700427',
    EMPRESA_IESS = 'ARTHURS AUDIT GLOBAL HURSDIT S.A.',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0919700427', 'ARTHURS AUDIT GLOBAL HURSDIT S.A.', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'ALVAREZ MAZON BYRON FRANCHESCO'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0918486655',
    EMPRESA_IESS = 'AUDIT HISPANIC PM HISPAUDIT S.A.',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0918486655', 'AUDIT HISPANIC PM HISPAUDIT S.A.', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'BARROSO FIGUEROA KEVIN ALEXANDER'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0927020388',
    EMPRESA_IESS = 'AUDIT HISPANIC PM HISPAUDIT S.A.',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0927020388', 'AUDIT HISPANIC PM HISPAUDIT S.A.', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'DELGADO PIGUAVE ALLISSON LISSETTE'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0951635952',
    EMPRESA_IESS = 'AUDIT HISPANIC PM HISPAUDIT S.A.',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0951635952', 'AUDIT HISPANIC PM HISPAUDIT S.A.', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'GUTIERREZ TEJADA JUAN CARLOS'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0926339094',
    EMPRESA_IESS = 'AUDIT HISPANIC PM HISPAUDIT S.A.',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0926339094', 'AUDIT HISPANIC PM HISPAUDIT S.A.', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'NAVARRETE DELGADO JAIME DANIEL'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0927468223',
    EMPRESA_IESS = 'AUDIT HISPANIC PM HISPAUDIT S.A.',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0927468223', 'AUDIT HISPANIC PM HISPAUDIT S.A.', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'ORTEGA VERA JOEL LEONARDO'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0952475317',
    EMPRESA_IESS = 'AUDIT HISPANIC PM HISPAUDIT S.A.',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0952475317', 'AUDIT HISPANIC PM HISPAUDIT S.A.', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'CHANO LOMAS JOSE ANTONIO'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0916568637',
    EMPRESA_IESS = 'BUADNET TAX&FINANCE',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0916568637', 'BUADNET TAX&FINANCE', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'SOLIS CALLE ALBERTO ISSAC'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0923774947',
    EMPRESA_IESS = 'BUADNET TAX&FINANCE',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0923774947', 'BUADNET TAX&FINANCE', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'SOTOMAYOR MENDOZA JAVIER ANTONIO'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '1205926924',
    EMPRESA_IESS = 'BUADNET TAX&FINANCE',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '1205926924', 'BUADNET TAX&FINANCE', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'MOLINA CARRILLO ROSMERY ELIZABETH'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0920207529',
    EMPRESA_IESS = 'BUSINESS ADVISOR NETWORK BUADNET S.A.',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0920207529', 'BUSINESS ADVISOR NETWORK BUADNET S.A.', SYSDATE);

-- PARRALES SOLIS UKLES XAVIER: ver nota "CASO ESPECIAL" arriba -- se
-- uso BUADNET por tener el aviso de entrada mas reciente.
MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'PARRALES SOLIS UKLES XAVIER'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0917023988',
    EMPRESA_IESS = 'BUSINESS ADVISOR NETWORK BUADNET S.A.',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0917023988', 'BUSINESS ADVISOR NETWORK BUADNET S.A.', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'PEÑA CRUZ ALEXANDER SANTIAGO'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0952165496',
    EMPRESA_IESS = 'EXPERTISE GLOBAL PBEXGLOBAL S.A.S',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0952165496', 'EXPERTISE GLOBAL PBEXGLOBAL S.A.S', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'OLVERA CARBO RONALD ENRQIUE'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0923547467',
    EMPRESA_IESS = 'KAVODLEX LEGAL & CORPORATE LC S.A.S.',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0923547467', 'KAVODLEX LEGAL & CORPORATE LC S.A.S.', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'AGUILAR SEGURA NATHALY JAZMIN'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0931785067',
    EMPRESA_IESS = 'LATINCONSULTING S.A.',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0931785067', 'LATINCONSULTING S.A.', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'BRIONES CARREÑO CARLOS VICENTE'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '1716108822',
    EMPRESA_IESS = 'LATINCONSULTING S.A.',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '1716108822', 'LATINCONSULTING S.A.', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'RODRIGUEZ CUENCA JOSE DANIEL'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0956662100',
    EMPRESA_IESS = 'LATINCONSULTING S.A.',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0956662100', 'LATINCONSULTING S.A.', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'ROSERO CHIQUITO LISBETH STEFANIA'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0955711403',
    EMPRESA_IESS = 'LATINCONSULTING S.A.',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0955711403', 'LATINCONSULTING S.A.', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'SOLIS CALLE NATALI LISBETH'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0923775068',
    EMPRESA_IESS = 'LATINCONSULTING S.A.',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0923775068', 'LATINCONSULTING S.A.', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'SOLIS PARRA MIGUEL VICENTE'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0957870306',
    EMPRESA_IESS = 'LATINCONSULTING S.A.',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0957870306', 'LATINCONSULTING S.A.', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'SOTOMAYOR MOINA REBECA ISABEL'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0932474711',
    EMPRESA_IESS = 'LATINCONSULTING S.A.',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0932474711', 'LATINCONSULTING S.A.', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'ACURIO MACIAS YERLY SULAY'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0955967179',
    EMPRESA_IESS = 'LUMIVENT PRO S.A.S',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0955967179', 'LUMIVENT PRO S.A.S', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'MERO AVELINO JORDAN OSWALDO'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0953562808',
    EMPRESA_IESS = 'LUMIVENT PRO S.A.S',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0953562808', 'LUMIVENT PRO S.A.S', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'MUÑOZ SOLIS JOSEPH ADRIAN'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0943314252',
    EMPRESA_IESS = 'LUMIVENT PRO S.A.S',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0943314252', 'LUMIVENT PRO S.A.S', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'TORRES ALVARADO YOLYI ANDRES'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0908147333',
    EMPRESA_IESS = 'LUMIVENT PRO S.A.S',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0908147333', 'LUMIVENT PRO S.A.S', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'NARANJO ESPINOZA DOMENICA VANESSA'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0951404649',
    EMPRESA_IESS = 'PMVISION S.A.S',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0951404649', 'PMVISION S.A.S', SYSDATE);

MERGE INTO VAC_CONFIG_USUARIO v
USING (
    SELECT IDUSUARIO FROM USUARIO
    WHERE UPPER(REGEXP_REPLACE(TRIM(APELLIDOS) || ' ' || TRIM(NOMBRE), '\s+', ' ')) = 'VARAS HERRERA CHRISTIAN PAUL'
) src ON (v.ID_USUARIO = src.IDUSUARIO)
WHEN MATCHED THEN UPDATE SET
    CEDULA = '0952167542',
    EMPRESA_IESS = 'PMVISION S.A.S',
    FECHA_ACTUALIZACION = SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_USUARIO, CEDULA, EMPRESA_IESS, FECHA_ACTUALIZACION)
    VALUES (src.IDUSUARIO, '0952167542', 'PMVISION S.A.S', SYSDATE);

COMMIT;

-- Verificar: deberian salir 36 filas. Cualquier nombre del excel que
-- no aparezca aqui es porque no encontro match exacto en USUARIO
-- (revisar tildes/orden de nombres y cargar ese caso a mano en
-- Vacaciones - Config.).
SELECT v.CEDULA, v.EMPRESA_IESS, u.NOMBRE, u.APELLIDOS
FROM VAC_CONFIG_USUARIO v
JOIN USUARIO u ON u.IDUSUARIO = v.ID_USUARIO
WHERE v.EMPRESA_IESS IS NOT NULL
ORDER BY v.EMPRESA_IESS, u.APELLIDOS;
