--------------------------------------------------------------------------
-- Modulo CAPACITACIONES: registro de seminarios/capacitaciones del grupo.
-- Lo administra unicamente SMORAN (permiso otorgado de forma individual,
-- no por departamento, igual que se hizo para Inventario en
-- docs/permisos/004_smoran_inventario_full.sql).
-- Ejecutar en la base de RRHH. Revisar y COMMIT al final.
--------------------------------------------------------------------------

-- 1. Permiso de acceso al modulo, otorgado solo a SMORAN.
INSERT INTO APP_PERMISO (ID_PERMISO, CODIGO, MODULO, DESCRIPCION, ESTADO)
VALUES (29, 'CAPACITACIONES_ACCESO', 'CAPACITACIONES', 'Acceso al modulo de Capacitaciones/Seminarios', 'A');

INSERT INTO APP_USUARIO_PERMISO (IDUSUARIO, ID_PERMISO, TIPO)
SELECT IDUSUARIO, 29, 'G' FROM USUARIO WHERE UPPER(USUARIO) = 'SMORAN';

-- 2. Catalogo de empresas capacitadoras (para el select + boton "Nueva").
CREATE TABLE CAPACITACIONES_EMPRESA (
    ID_EMPRESA  NUMBER NOT NULL,
    DESCRIPCION VARCHAR2(300) NOT NULL,
    ESTADO      CHAR(1) DEFAULT 'A' NOT NULL,
    CONSTRAINT PK_CAPAC_EMPRESA PRIMARY KEY (ID_EMPRESA),
    CONSTRAINT CK_CAPAC_EMPRESA_ESTADO CHECK (ESTADO IN ('A','I'))
);

-- Semilla con las empresas capacitadoras ya usadas en el registro excel.
INSERT INTO CAPACITACIONES_EMPRESA (ID_EMPRESA, DESCRIPCION) VALUES (1, 'AEQ ASESORES TRIBUTARIOS S.A.');
INSERT INTO CAPACITACIONES_EMPRESA (ID_EMPRESA, DESCRIPCION) VALUES (2, 'COLEGIO DE CONTADORES PUBLICOS DE PICHINCHA Y ECUADOR');
INSERT INTO CAPACITACIONES_EMPRESA (ID_EMPRESA, DESCRIPCION) VALUES (3, 'VCR VANEGAS S.A');
INSERT INTO CAPACITACIONES_EMPRESA (ID_EMPRESA, DESCRIPCION) VALUES (4, 'IDEALES CONSULTING S.A. IDETINGSA');
INSERT INTO CAPACITACIONES_EMPRESA (ID_EMPRESA, DESCRIPCION) VALUES (5, 'PROFINGE S.A.S');
INSERT INTO CAPACITACIONES_EMPRESA (ID_EMPRESA, DESCRIPCION) VALUES (6, 'CAMARA DE COMERCIO ECUATORIANO CANADIENSE DE GUAYAQUIL');
INSERT INTO CAPACITACIONES_EMPRESA (ID_EMPRESA, DESCRIPCION) VALUES (7, 'CHAVEZ CHAVEZ LUIS ALFONSO');
INSERT INTO CAPACITACIONES_EMPRESA (ID_EMPRESA, DESCRIPCION) VALUES (8, 'UNIVERSIDAD PARTICULAR DE ESPECIALIDADES ESPIRITU SANTO');
INSERT INTO CAPACITACIONES_EMPRESA (ID_EMPRESA, DESCRIPCION) VALUES (9, 'LIDERAZGO CAPACITACION Y CONSULTORIA DAVSOC COMPAÑÍA LIMITADA');

-- 3. Registro de seminarios/capacitaciones.
CREATE TABLE CAPACITACIONES_SEMINARIO (
    ID_SEMINARIO         NUMBER NOT NULL,
    ID_EMPRESA           NUMBER,
    NOMBRE_SEMINARIO     VARCHAR2(500) NOT NULL,
    ESTADO_PAGO          VARCHAR2(20) NOT NULL,
    FORMA_PAGO           VARCHAR2(20),
    APROBACION           VARCHAR2(200),
    HORARIO              VARCHAR2(100),
    FECHA_CAPACITACION   VARCHAR2(300),
    DURACION_HORAS       NUMBER(6,2),
    MODALIDAD            VARCHAR2(20),
    UBICACION            VARCHAR2(300),
    NO_PARTICIPANTES     NUMBER,
    NOMBRE_PARTICIPANTES VARCHAR2(1000),
    SUBTOTAL             NUMBER(12,2) DEFAULT 0 NOT NULL,
    IVA_PORCENTAJE       NUMBER(5,2) DEFAULT 15 NOT NULL,
    IVA_VALOR            NUMBER(12,2) DEFAULT 0 NOT NULL,
    TOTAL_FACTURA        NUMBER(12,2) DEFAULT 0 NOT NULL,
    RETENCION            NUMBER(12,2) DEFAULT 0 NOT NULL,
    TOTAL_PAGADO         NUMBER(12,2) DEFAULT 0 NOT NULL,
    COMPANIA_FACTURA     VARCHAR2(300),
    FECHA_FACTURA        DATE,
    ACTIVO               CHAR(1) DEFAULT 'A' NOT NULL,
    ID_USUARIO_CREA      NUMBER NOT NULL,
    FECHA_CREACION       DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CAPAC_SEMINARIO PRIMARY KEY (ID_SEMINARIO),
    CONSTRAINT CK_CAPAC_SEM_ACTIVO CHECK (ACTIVO IN ('A','I')),
    CONSTRAINT CK_CAPAC_SEM_ESTADOPAGO CHECK (ESTADO_PAGO IN ('PAGADO','POR COBRAR')),
    CONSTRAINT CK_CAPAC_SEM_FORMAPAGO CHECK (FORMA_PAGO IN ('EFECTIVO','TRANSFERENCIA','CHEQUE','CANJE')),
    CONSTRAINT CK_CAPAC_SEM_MODALIDAD CHECK (MODALIDAD IN ('PRESENCIAL','ONLINE')),
    CONSTRAINT FK_CAPAC_SEM_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES CAPACITACIONES_EMPRESA(ID_EMPRESA),
    CONSTRAINT FK_CAPAC_SEM_USUARIO FOREIGN KEY (ID_USUARIO_CREA) REFERENCES USUARIO(IDUSUARIO)
);

-- 4. Verificacion.
SELECT * FROM CAPACITACIONES_EMPRESA ORDER BY ID_EMPRESA;
SELECT p.CODIGO, u.USUARIO FROM APP_PERMISO p
  JOIN APP_USUARIO_PERMISO up ON up.ID_PERMISO = p.ID_PERMISO
  JOIN USUARIO u ON u.IDUSUARIO = up.IDUSUARIO
  WHERE p.CODIGO = 'CAPACITACIONES_ACCESO';

-- Si todo bien: COMMIT;  Si no: ROLLBACK;
