--------------------------------------------------------------------------
-- Modulo LEGAL: Control y Seguimiento -> Investigacion Previa (IP)
-- Crea el permiso de acceso (solo departamento LEGAL), el catalogo de
-- delitos, la cabecera de investigaciones previas y su detalle de
-- seguimientos (uno a muchos).
-- Ejecutar en la base de RRHH. Revisar y COMMIT al final.
--------------------------------------------------------------------------

-- 1. Permiso de acceso al modulo, concedido solo al departamento LEGAL.
INSERT INTO APP_PERMISO (ID_PERMISO, CODIGO, MODULO, DESCRIPCION, ESTADO)
VALUES (28, 'LEGAL_ACCESO', 'LEGAL', 'Acceso al modulo Legal (Control y Seguimiento)', 'A');

INSERT INTO APP_DEPARTAMENTO_PERMISO (DEPARTAMENTO, ID_PERMISO, TIPO)
VALUES ('LEGAL', 28, 'G');

-- 2. Catalogo de delitos (para el select + boton "Nuevo delito").
CREATE TABLE LEGAL_DELITO (
    ID_DELITO   NUMBER NOT NULL,
    DESCRIPCION VARCHAR2(200) NOT NULL,
    ESTADO      CHAR(1) DEFAULT 'A' NOT NULL,
    CONSTRAINT PK_LEGAL_DELITO PRIMARY KEY (ID_DELITO),
    CONSTRAINT CK_LEGAL_DELITO_ESTADO CHECK (ESTADO IN ('A','I'))
);

-- Semilla con los delitos ya usados en el registro de la excel del
-- departamento (evita que empiecen con el catalogo vacio).
INSERT INTO LEGAL_DELITO (ID_DELITO, DESCRIPCION) VALUES (1, 'DAÑOS MATERIALES');
INSERT INTO LEGAL_DELITO (ID_DELITO, DESCRIPCION) VALUES (2, 'ESTAFA');
INSERT INTO LEGAL_DELITO (ID_DELITO, DESCRIPCION) VALUES (3, 'DEFRAUDACIÓN TRIBUTARIA');
INSERT INTO LEGAL_DELITO (ID_DELITO, DESCRIPCION) VALUES (4, 'LESIONES CAUSADAS POR ACC. DE TRANSITO');
INSERT INTO LEGAL_DELITO (ID_DELITO, DESCRIPCION) VALUES (5, 'SECUESTRO');
INSERT INTO LEGAL_DELITO (ID_DELITO, DESCRIPCION) VALUES (6, 'FALSIFICACIÓN Y USO DE DOCUMENTO FALSO');
INSERT INTO LEGAL_DELITO (ID_DELITO, DESCRIPCION) VALUES (7, 'HURTO');
INSERT INTO LEGAL_DELITO (ID_DELITO, DESCRIPCION) VALUES (8, 'EXTORSIÓN');
INSERT INTO LEGAL_DELITO (ID_DELITO, DESCRIPCION) VALUES (9, 'ROBO/SECUESTRO');
INSERT INTO LEGAL_DELITO (ID_DELITO, DESCRIPCION) VALUES (10, 'ROBO');

-- 3. Cabecera de Investigacion Previa.
CREATE TABLE LEGAL_IP (
    ID_LEGAL_IP      NUMBER NOT NULL,
    PROCESADO        VARCHAR2(500),
    VICTIMA          VARCHAR2(500),
    PROCESO          VARCHAR2(500),
    ID_DELITO        NUMBER,
    FISCALIA         VARCHAR2(300),
    UBICACION        VARCHAR2(150),
    ESTADO           CHAR(1) DEFAULT 'A' NOT NULL,
    ID_USUARIO_CREA  NUMBER NOT NULL,
    FECHA_CREACION   DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_LEGAL_IP PRIMARY KEY (ID_LEGAL_IP),
    CONSTRAINT CK_LEGAL_IP_ESTADO CHECK (ESTADO IN ('A','I')),
    CONSTRAINT FK_LEGAL_IP_DELITO FOREIGN KEY (ID_DELITO) REFERENCES LEGAL_DELITO(ID_DELITO),
    CONSTRAINT FK_LEGAL_IP_USUARIO FOREIGN KEY (ID_USUARIO_CREA) REFERENCES USUARIO(IDUSUARIO)
);

-- 4. Seguimientos de cada Investigacion Previa (uno a muchos).
CREATE TABLE LEGAL_IP_SEGUIMIENTO (
    ID_SEGUIMIENTO   NUMBER NOT NULL,
    ID_LEGAL_IP      NUMBER NOT NULL,
    DESCRIPCION      VARCHAR2(1000) NOT NULL,
    ID_USUARIO_CREA  NUMBER NOT NULL,
    FECHA_CREACION   DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_LEGAL_IP_SEGUIMIENTO PRIMARY KEY (ID_SEGUIMIENTO),
    CONSTRAINT FK_SEGUIMIENTO_IP FOREIGN KEY (ID_LEGAL_IP) REFERENCES LEGAL_IP(ID_LEGAL_IP),
    CONSTRAINT FK_SEGUIMIENTO_USUARIO FOREIGN KEY (ID_USUARIO_CREA) REFERENCES USUARIO(IDUSUARIO)
);

-- 5. Verificacion.
SELECT * FROM LEGAL_DELITO ORDER BY ID_DELITO;
SELECT p.CODIGO, dp.DEPARTAMENTO FROM APP_PERMISO p
  JOIN APP_DEPARTAMENTO_PERMISO dp ON dp.ID_PERMISO = p.ID_PERMISO
  WHERE p.CODIGO = 'LEGAL_ACCESO';

-- Si todo bien: COMMIT;  Si no: ROLLBACK;
