--------------------------------------------------------------------------
-- Modulo LEGAL: Control y Seguimiento -> EXPEL
-- Reutiliza el permiso LEGAL_ACCESO ya creado en 001_modulo_legal.sql
-- (no requiere permiso nuevo). Crea los catalogos de Materia y Tipo de
-- Accion, la cabecera de EXPEL y su detalle de seguimientos.
-- Ejecutar en la base de RRHH. Revisar y COMMIT al final.
--------------------------------------------------------------------------

-- 1. Catalogo de materias (para el select + boton "Nueva materia").
CREATE TABLE LEGAL_MATERIA (
    ID_MATERIA  NUMBER NOT NULL,
    DESCRIPCION VARCHAR2(200) NOT NULL,
    ESTADO      CHAR(1) DEFAULT 'A' NOT NULL,
    CONSTRAINT PK_LEGAL_MATERIA PRIMARY KEY (ID_MATERIA),
    CONSTRAINT CK_LEGAL_MATERIA_ESTADO CHECK (ESTADO IN ('A','I'))
);

-- Semilla con las materias ya usadas en el registro de la excel del
-- departamento (pestaña EXPEL).
INSERT INTO LEGAL_MATERIA (ID_MATERIA, DESCRIPCION) VALUES (1, 'PENAL');
INSERT INTO LEGAL_MATERIA (ID_MATERIA, DESCRIPCION) VALUES (2, 'CONTENCIOSO TRIBUTARIO');
INSERT INTO LEGAL_MATERIA (ID_MATERIA, DESCRIPCION) VALUES (3, 'FAMILIA MUJER NIÑEZ Y ADOLESCENCIA');
INSERT INTO LEGAL_MATERIA (ID_MATERIA, DESCRIPCION) VALUES (4, 'TRÁNSITO');
INSERT INTO LEGAL_MATERIA (ID_MATERIA, DESCRIPCION) VALUES (5, 'CIVIL');

-- 2. Catalogo de tipo de accion (para el select + boton "Nuevo tipo de accion").
CREATE TABLE LEGAL_TIPO_ACCION (
    ID_TIPO_ACCION NUMBER NOT NULL,
    DESCRIPCION    VARCHAR2(200) NOT NULL,
    ESTADO         CHAR(1) DEFAULT 'A' NOT NULL,
    CONSTRAINT PK_LEGAL_TIPO_ACCION PRIMARY KEY (ID_TIPO_ACCION),
    CONSTRAINT CK_LEGAL_TIPOACCION_ESTADO CHECK (ESTADO IN ('A','I'))
);

INSERT INTO LEGAL_TIPO_ACCION (ID_TIPO_ACCION, DESCRIPCION) VALUES (1, 'ACCIÓN PENAL PÚBLICA');
INSERT INTO LEGAL_TIPO_ACCION (ID_TIPO_ACCION, DESCRIPCION) VALUES (2, 'ACCIÓN DE IMPUGNACIÓN');
INSERT INTO LEGAL_TIPO_ACCION (ID_TIPO_ACCION, DESCRIPCION) VALUES (3, 'SUMARIO');
INSERT INTO LEGAL_TIPO_ACCION (ID_TIPO_ACCION, DESCRIPCION) VALUES (4, 'CONTRAVENCIONES DE TRÁNSITO');
INSERT INTO LEGAL_TIPO_ACCION (ID_TIPO_ACCION, DESCRIPCION) VALUES (5, 'DILIGENCIA PREPARATORIA');
INSERT INTO LEGAL_TIPO_ACCION (ID_TIPO_ACCION, DESCRIPCION) VALUES (6, 'DELITOS DE TRÁNSITO');

-- 3. Cabecera de EXPEL.
CREATE TABLE LEGAL_EXPEL (
    ID_LEGAL_EXPEL   NUMBER NOT NULL,
    ACTOR            VARCHAR2(500),
    DEMANDADO        VARCHAR2(500),
    JUICIO           VARCHAR2(100),
    ID_MATERIA       NUMBER,
    ID_TIPO_ACCION   NUMBER,
    ASUNTO           VARCHAR2(1000),
    LUGAR            VARCHAR2(300),
    ESTADO           CHAR(1) DEFAULT 'A' NOT NULL,
    ID_USUARIO_CREA  NUMBER NOT NULL,
    FECHA_CREACION   DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_LEGAL_EXPEL PRIMARY KEY (ID_LEGAL_EXPEL),
    CONSTRAINT CK_LEGAL_EXPEL_ESTADO CHECK (ESTADO IN ('A','I')),
    CONSTRAINT FK_LEGAL_EXPEL_MATERIA FOREIGN KEY (ID_MATERIA) REFERENCES LEGAL_MATERIA(ID_MATERIA),
    CONSTRAINT FK_LEGAL_EXPEL_TIPOACCION FOREIGN KEY (ID_TIPO_ACCION) REFERENCES LEGAL_TIPO_ACCION(ID_TIPO_ACCION),
    CONSTRAINT FK_LEGAL_EXPEL_USUARIO FOREIGN KEY (ID_USUARIO_CREA) REFERENCES USUARIO(IDUSUARIO)
);

-- 4. Seguimientos de cada EXPEL (uno a muchos).
CREATE TABLE LEGAL_EXPEL_SEGUIMIENTO (
    ID_SEGUIMIENTO    NUMBER NOT NULL,
    ID_LEGAL_EXPEL    NUMBER NOT NULL,
    DESCRIPCION       VARCHAR2(1000) NOT NULL,
    ID_USUARIO_CREA   NUMBER NOT NULL,
    FECHA_CREACION    DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_LEGAL_EXPEL_SEGUIMIENTO PRIMARY KEY (ID_SEGUIMIENTO),
    CONSTRAINT FK_SEGUIMIENTO_EXPEL FOREIGN KEY (ID_LEGAL_EXPEL) REFERENCES LEGAL_EXPEL(ID_LEGAL_EXPEL),
    CONSTRAINT FK_SEGUIMIENTO_EXPEL_USUARIO FOREIGN KEY (ID_USUARIO_CREA) REFERENCES USUARIO(IDUSUARIO)
);

-- 5. Verificacion.
SELECT * FROM LEGAL_MATERIA ORDER BY ID_MATERIA;
SELECT * FROM LEGAL_TIPO_ACCION ORDER BY ID_TIPO_ACCION;

-- Si todo bien: COMMIT;  Si no: ROLLBACK;
